const assert=require('node:assert/strict');
const api=require('../assets/distribution-unprogram.js');
const row=(id,date,extra={})=>({id,distributionId:'D',date,slot:'08H',status:'PENDENTE',qty:1,channel:'RÁDIO',...extra});
const data={months:{'2026-09':{items:[row('before','2026-09-30'),row('wrong-storage','2026-10-12')]},'2026-10':{items:[row('A','2026-10-10'),row('B','2026-10-11',{channel:'APP'}),row('done','2026-10-10',{status:'REALIZADO'}),row('winner','2026-10-10',{winnerNames:['ANA']}),row('profile','2026-10-10',{resultWinners:[{instagram:'@ana'}]}),row('promo','2026-10-10',{sourceType:'promo-result',promoId:'P'}),row('cancel','2026-10-10',{status:'CANCELADO'}),row('other','2026-10-10',{distributionId:'OTHER'})],promos:[{id:'P',distributionId:'D',startDate:'2026-10-01',endDate:'2026-10-31'}]},'2026-11':{items:[row('future','2026-11-01')]}}};
const opts={distributionIds:['D'],month:'2026-10',mode:'month'};
let plan=api.plan(data,opts);
assert.deepEqual(plan.removable.map(r=>r.item.id).sort(),['A','B','wrong-storage']);
assert.equal(plan.protected.length,5);
assert.equal(plan.promos.length,1);
assert.deepEqual(plan.dates,['2026-10-10','2026-10-11','2026-10-12']);
assert.deepEqual(api.plan(data,{...opts,mode:'day',day:'2026-10-10'}).removable.map(r=>r.item.id),['A']);
assert.deepEqual(api.plan(data,{...opts,mode:'range',start:'2026-10-11',end:'2026-11-01'}).removable.map(r=>r.item.id).sort(),['B','future','wrong-storage']);
assert.equal(api.plan(data,{...opts,mode:'all'}).removable.length,5);
assert.throws(()=>api.plan(data,{...opts,mode:'range',start:'2026-10-20',end:'2026-10-10'}),/PERÍODO/);
assert.throws(()=>api.plan(data,{...opts,mode:'day',day:'2026-02-30'}),/DATA/);
const candidates=plan.removable.filter(r=>r.monthKey==='2026-10');
let result=api.applyMonth(data.months['2026-10'],candidates,{id:'OP',createdAt:'2026-10-09T17:00:00Z'});
assert.deepEqual(result.removed.map(i=>i.id),['A','B']);
assert.ok(result.month.items.some(i=>i.id==='done'));
assert.ok(result.month.items.some(i=>i.id==='other'));
assert.equal(data.months['2026-10'].items.length,8,'planner must not mutate original state');
const remote=structuredClone(data.months['2026-10']);remote.items.find(i=>i.id==='A').winnerName='NOVA GANHADORA';remote.items.find(i=>i.id==='B').date='2026-10-15';remote.items.push(row('new','2026-10-10'));
result=api.applyMonth(remote,candidates,{id:'OP2',createdAt:'2026-10-09T17:00:00Z'});
assert.equal(result.removed.length,0);assert.equal(result.skipped.length,2);assert.ok(result.month.items.some(i=>i.id==='new'));
assert.equal(api.applyMonth(result.month,candidates,{id:'OP2'}).removed.length,0,'retry must not remove a changed item');
const duplicates=structuredClone(data);duplicates.months['2026-09'].items.push(row('A','2026-10-10',{status:'REALIZADO'}));
assert.ok(!api.plan(duplicates,opts).removable.some(r=>r.item.id==='A'));
console.log('PASS: scope, hidden links, winner/history safety, concurrent edits, idempotency and duplicate protection');
